### PR TITLE
Adding app-added charity users to charities map 

### PR DESCRIPTION
**Pull request by pkhodadoustan**

### CODE REVIEW

**Review by priyalsuneja — COMMENTED** [review]
Can we add a logout link to "Your page"?

**Review by priyalsuneja — COMMENTED** [review]
Also, the your page still shows "Charities" and "Community" instead of "Charities Map" and "Charities Community"

**Comment by priyalsuneja** [comment]
A very important thing: when a charity sets any link, like "Contact Us", it redirects to localhost:8080/link. 
For eg, if they set "www.google.com", it would redirect to "http://localhost:8080/www.google.com" instead of "www.google.com". Can we change this?

**Review by priyalsuneja — CHANGES_REQUESTED** [review]
is it possible to fix these issues? I can help you with whatever you like

**Comment by pkhodadoustan** [comment]
so I go in the order you have asked: 
- This is a Charties page, so the logout feature is not about this pull request. Even if we want to add log out to yourpage, I think we can do it later because the code we have for login/logout is the original one that is given to us, I haven't changed it at all.
- I will change the nav bar of your page I think I missed that one, thanks for letting me know about it :)
-I just checked the link setting functionality on the live server and its working fine! so there is no issue with that! if you set it to any page it would go to that page, and this this pull request does not change that code at all.
-so there is only one issue to fix in this pull request the nav bar of your page, I'll fix it right now

**Comment by priyalsuneja** [comment]
Looks good to me!!

**Review by priyalsuneja — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
